### ISSUE TITLE
Self Hosted / Restrict User Signup

### ISSUE THREAD

**Issue by bassmaster187** [exceptionless/Exceptionless#1035]
I have a self hosted exceptionless instance on docker:

```
version: "3"
services:

  exceptionless:
    image: exceptionless/exceptionless:latest
    restart: always
    volumes:
      - /volume1/docker/exceptionless/esdata:/usr/share/elasticsearch/data
    ports:
      - 5002:80

```

I realized anybody can signup on my server and can create their own projects. Is it possible to restrict this by any config? How can list all users on my instance and delete them?
