### ISSUE TITLE
Selfhosted - More information needed

### ISSUE THREAD

**Issue by JoshTickles** [exceptionless/Exceptionless#1055]
Hey all - I've almost got this running in my self hosted k8s clusters. 

I'm just after a bit more information about the following 2 vars in the example scripts you have. 

https://github.com/exceptionless/Exceptionless/tree/master/k8s
storage.connectionString
queue.connectionString

Is anyone able to let me know what are these used for, and what would an example be for a locally hosted k8s cluster (i.e not in Azure or AWS)?

cheers

**Comment by niemyjski** [comment]
They are used to configure the different abstractions. Since you are using multiple processes you would want to configure it to not use the in memory implementations.

```yaml
Redis: server="localhost,abortConnect=false"
Cache: provider=redis;
MessageBus: provider=redis;
Queue: provider=redis;
Storage: provider=folder;path=/mnt/my_storage_path
```
