### ISSUE TITLE
Default docker-compose CORS failed

### ISSUE THREAD

**Issue by veraciousnottaken** [exceptionless/Exceptionless#1197]
Using default [https://raw.githubusercontent.com/exceptionless/Exceptionless/main/docker-compose.yml](docker-compose) 
```
ui:
    image: exceptionless/ui:latest
    environment:
      AppMode: Development
      EX_ApiUrl: http://10.80.9.153:5000
      EX_Html5Mode: 'true'
    ports:
      - 5100:80

volumes:
  certs:
    driver: local
  esdata:
    driver: local
```
On login screen http://x.x.x.x:5100/login type any credentials, in result:

![obraz](https://user-images.githubusercontent.com/2012946/207871995-42a5063c-d4da-40cc-b4bb-19efafa318ff.png)

![obraz](https://user-images.githubusercontent.com/2012946/207871719-01088d50-52ae-46e8-8f55-f8bb773aa2c2.png)
```
OPTIONS /api/v2/auth/login undefined
Host: 10.80.9.153:5000
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0
Accept: */*
Accept-Language: pl,en;q=0.7,en-US;q=0.3
Accept-Encoding: gzip, deflate
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type
Referer: http://10.80.9.153:5100/
Origin: http://10.80.9.153:5100
DNT: 1
Connection: keep-alive
```
![obraz](https://user-images.githubusercontent.com/2012946/207871787-d7d0c78d-4163-4391-a15e-1f23ba2a4ee9.png)
```
POST /api/v2/auth/login undefined
Host: 10.80.9.153:5000
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0
Accept: application/json, text/plain, */*
Accept-Language: pl,en;q=0.7,en-US;q=0.3
Accept-Encoding: gzip, deflate
Content-Type: application/json;charset=utf-8
Content-Length: 45
Origin: http://10.80.9.153:5100
DNT: 1
Connection: keep-alive
Referer: http://10.80.9.153:5100/
```
