### ISSUE TITLE
docker-compose references Redis ConnectionString

### ISSUE THREAD

**Issue by Sc7-git** [exceptionless/Exceptionless#1752]
I have a Redis service and have written the following configuration based on samples/docker-compose.yml:
```
version: "3.7"

services:
  app:
    depends_on:
      - elasticsearch
    image: exceptionless/app:latest
    environment:
      EX_AppMode: Production
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://elasticsearch:9200
      EX_ConnectionStrings__MessageBus: provider=redis
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=192.168.1.13:6379,password=123999,defaultDatabase=1,ssl=false,abortConnect=false
      #EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
      #ASPNETCORE_HTTPS_PORT: 5201
      ASPNETCORE_URLS: http://+
      #ASPNETCORE_URLS: http://+;https://+
      #ASPNETCORE_Kestrel__Certificates__Default__Password: password
      #ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      EX_RunJobsInProcess: "false"
    ports:
      - 5200:80
    volumes:
      - ex_appdata:/app/storage
      - ex_ssldata:/https
    #restart: always
```

However, the operation was unsuccessful. May I ask how to reference Redis using a connection string.
