### ISSUE TITLE
Ubuntu is normal, CentOS is reporting an error. BackgroundService failed

### ISSUE THREAD

**Issue by Sc7-git** [exceptionless/Exceptionless#1779]
exceptionless-app-1            | [09:29:17 ERR] Unable to start closeinactivesessions job due to startup actions failure
exceptionless-app-1            | [09:29:17 ERR] Unable to start dailysummary job due to startup actions failure
exceptionless-app-1            | [09:29:17 ERR] Unable to start eventnotifications job due to startup actions failure
exceptionless-app-1            | [09:29:17 ERR] Unable to start eventposts job due to startup actions failure
exceptionless-app-1            | [09:29:17 ERR] Unable to start eventuserdescriptions job due to startup actions failure
exceptionless-app-1            | [09:29:17 ERR] Unable to start mailmessage job due to startup actions failure
exceptionless-app-1            | [09:29:17 ERR] Unable to start stackstatus job due to startup actions failure
exceptionless-app-1            | [09:29:17 ERR] Unable to start stackeventcount job due to startup actions failure
exceptionless-app-1            | [09:29:17 ERR] Unable to start webhooks job due to startup actions failure
exceptionless-app-1            | [09:29:17 ERR] Unable to start workitem job due to startup actions failure
exceptionless-app-1            | [09:29:17 ERR] Unable to start eventusage job due to startup actions failure
exceptionless-app-1            | [09:29:17 ERR] BackgroundService failed

```
version: "3.7"

services:
  app:
    depends_on:
      - elasticsearch
    image: exceptionless/app:8.0.4
    environment:
      EX_AppMode: Production
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://elasticsearch:9200
      EX_ConnectionStrings__MessageBus: provider=redis
      EX_ConnectionStrings__Redis: server=*,password=*,defaultDatabase=1,ssl=false,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
      EX_RunJobsInProcess: "true"
      EX_EnableAccountCreation: false
    ports:
      - 5300:80
    volumes:
      - ex_appdata:/app/storage
      - ex_ssldata:/https
    restart: always
    security_opt:
      - seccomp:unconfined
```
