### ISSUE TITLE
got error "Unable to retrieve payload xxxx"

### ISSUE THREAD

**Issue by witskeeper** [exceptionless/Exceptionless#408]
got error "Unable to retrieve payload xxxx" 

i deploy master code in docker ， on 2 server behind load balance service
got error random:
[09:21:34 ERR] Job run EventPostsJob failed: Unable to retrieve payload 'archive/19/03/15/09/21/5c89cbce620cd800019e6d5e/f36af1d984e74f78992d82f1fe24e5bc.payload'.

my config:
```
---
ConnectionStrings:
  Elasticsearch: server=http://xxxxxx.com:9200;username=elastic;password=xxxxxx
  Cache: provider=redis;server="redis.xxxx,password=xxxxxxx,defaultDatabase=5"
  MessageBus: provider=redis;server="redis.xxxx,password=xxxxxxx,defaultDatabase=5"
#  Metrics: provider=statsd;server=10.0.0.5;
  Queue: provider=redis;server="redis.xxxx,password=xxxxxxx,defaultDatabase=5"
  Storage: provider=folder;path=.\storage
  Email: 'smtps://xxxx%xxxxx.com:xxxxxx@smtp.xxxx.xxxx.com:465'
#  LDAP: ''
#  OAuth: FacebookId=395178683904310;GitHubId=7ef1dd5bfbc4ccf7f5ef;GoogleId=809763155066-enkkdmt4ierc33q9cft9nf5d5c02h30q.apps.googleusercontent.com;MicrosoftId=000000004C137E8B;SlackId=34500115540.177239122322;

  # Base url for the ui used to build links in emails and other places.
BaseURL: https://xxxx.xxxx.xxxx/#!
# Controls whether users can signup.
EnableAccountCreation: false
RunJobsInProcess: true
# Email
SmtpFrom: noreply@xxxxxx.com

# Exceptionless Client Settings
#ExceptionlessServerUrl: https://collector.exceptionless.io
#InternalProjectId: 50ca6b2423d6c8493020b823
#StripePublishableApiKey: pk_live_QTiVo5Fqv7uNScqIpd1Ns9gX

```
