### ISSUE TITLE
I have some problems with the docker compose deployment.

### ISSUE THREAD

**Issue by quan01994** [exceptionless/Exceptionless#428]
````
version: '3.4'

services:
  api:
    depends_on:
      - elasticsearch
      - redis
    build:
      context: .
      target: api
    image: exceptionless/api-ci:latest
    environment:
      EX_AppMode: Production
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://elasticsearch:9200
      #EX_ConnectionStrings__Email: smtps://user:password@smtp.host.com:587
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
      EX_RunJobsInProcess: 'false'
    ports:
      - 5050:80
    volumes:
      - C:/docker/volume/exceptionless/appdata:/app/storage

  jobs:
    depends_on:
      - api
    build:
      context: .
      target: job
    image: exceptionless/job-ci:latest
    command: run-all
    environment:
      EX_AppMode: Production
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://elasticsearch:9200
      #EX_ConnectionStrings__Email: smtps://user:password@smtp.host.com:587
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
    volumes:
      - C:/docker/volume/exceptionless/appdata:/app/storage

  ui:
    image: exceptionless/ui-ci:latest
    environment:
      AppMode: Development
      EX_ApiUrl: http://localhost:5050
    ports:
      - 5100:80

  elasticsearch:
    image: exceptionless/elasticsearch:1
    environment:
      cluster.name: 'exceptionless'
      bootstrap.memory_lock: 'true'
      discovery.type: single-node
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      xpack.security.enabled: 'false'
      xpack.graph.enabled: 'false'
      xpack.watcher.enabled: 'false'
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - C:/docker/volume/exceptionless/esdata:/usr/share/elasticsearch/data

  # kibana:
  #   depends_on:
  #     - elasticsearch
  #   image: exceptionless/kibana:1
  #   environment:
  #     xpack.security.enabled: 'false'
  #   ports:
  #     - 5601:5601

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
````

api have some problems when i search infomation

[08:31:14 ERR] Error getting mapping for index events
Server Error (Index=events Type=index_not_found_exception): no such index
[404] GET /events/_mapping/events

[08:31:14 ERR] Error getting mapping for index events
Server Error (Index=events Type=index_not_found_exception): no such index
[404] GET /events/_mapping/events
![image](https://user-images.githubusercontent.com/20533465/59666787-1d358e00-91e8-11e9-9d16-a7817a978025.png)

this is es log
![image](https://user-images.githubusercontent.com/20533465/59666873-4a823c00-91e8-11e9-8e42-bca3373aeb0a.png)

**Comment by niemyjski** [comment]
Can you hit Elasticsearch on port 9200? I'd make sure that's exposed and you can hit it.

**Comment by quan01994** [comment]
![image](https://user-images.githubusercontent.com/20533465/59892783-23588400-940d-11e9-87c8-5a3d2fa1a036.png)
Visible in the browser

**Comment by niemyjski** [comment]
If you run `GET _cat/indicies` in elastic search is there any indices. It's like it cannot talk to it. That docker compose file won't even run on my machine. Have you just tried using ours as is? Can you do `docker-compose up elasticsearch redis` and then clone this repository and copy some of the config to the yaml file in the web project and start debugging? It might say a different error (I'm really curious what the error is).

**Comment by quan01994** [comment]
![image](https://user-images.githubusercontent.com/20533465/59999346-55c7e280-9694-11e9-84c9-c8f2b5132a51.png)

400 bad request

**Comment by niemyjski** [comment]
Here is the link to documentation: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/cat-indices.html

**Comment by napoleonjang** [comment]
> Here is the link to documentation: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/cat-indices.html

I encountered the same problem, however, the elasticsearch _cat/indices command runs successfully:
![image](https://user-images.githubusercontent.com/2639201/60424028-05b3c780-9c22-11e9-9c05-105c8464456e.png)

It seams like  index "events“ not built in  elasticsearch  ?

**Comment by quan01994** [comment]
````
version: '3.4'

services:
  api:
    depends_on:
      - elasticsearch
      - redis
    image: exceptionless/api-ci:latest
    container_name: ex_api
    environment:
      EX_AppMode: Production
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://elasticsearch:9200
      #EX_ConnectionStrings__Email: smtps://user:password@smtp.host.com:587
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
      EX_RunJobsInProcess: 'false'
    ports:
      - 5000:80
    volumes:
      - C:/docker/volume/exceptionless/appdata:/app/storage

  jobs:
    depends_on:
      - api
    image: exceptionless/job-ci:latest
    container_name: ex_job
    command: run-all
    environment:
      EX_AppMode: Production
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://elasticsearch:9200
      #EX_ConnectionStrings__Email: smtps://user:password@smtp.host.com:587
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
    volumes:
      - C:/docker/volume/exceptionless/appdata:/app/storage

  ui:
    image: exceptionless/ui-ci:latest
    container_name: ex_ui
    environment:
      AppMode: Development
      BaseUrl: http://localhost:5000
      EX_ApiUrl: http://localhost:5000
    ports:
      - 5100:80

  elasticsearch:
    container_name: ex_es
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    environment:
      cluster.name: 'exceptionless'
      bootstrap.memory_lock: 'true'
      discovery.type: single-node
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      xpack.security.enabled: 'false'
      xpack.graph.enabled: 'false'
      xpack.watcher.enabled: 'false'
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - C:/docker/volume/exceptionless/esdata:/usr/share/elasticsearch/data

  # kibana:
  #   depends_on:
  #     - elasticsearch
  #   image: exceptionless/kibana:1
  #   environment:
  #     xpack.security.enabled: 'false'
  #   ports:
  #     - 5601:5601

  redis:
    container_name: ex_redis
    image: redis:alpine
    ports:
      - 6379:6379
````
Still have problems
![image](https://user-images.githubusercontent.com/20533465/60644820-c4155d80-9e69-11e9-8bb9-1bfd612b307e.png)

![image](https://user-images.githubusercontent.com/20533465/60644853-d5f70080-9e69-11e9-89a7-30caaa96fa25.png)
