### ISSUE TITLE
User session statistics graph has no data？

### ISSUE THREAD

**Issue by yuefengkai** [exceptionless/Exceptionless#792]
### User session statistics graph has no data
![image](https://user-images.githubusercontent.com/2100585/100366201-7f302f00-303b-11eb-84bb-3d3bc4eeaebc.png)

### jobs-close-inactive-sessions log
![image](https://user-images.githubusercontent.com/2100585/100366660-0f6e7400-303c-11eb-93a5-a2852873201c.png)

**Comment by niemyjski** [comment]
Hello,

Thanks for reaching out to us. What version of Exceptionless are you using? Was this working before?

**Comment by yuefengkai** [comment]
exceptionless/api:7.0.7
The same project uses the old version of exceptionless (4.1.2861 359390c442) with statistics

The following link is my server configuration
https://github.com/exceptionless/Exceptionless/issues/779

**Comment by niemyjski** [comment]
Did you run the migrations for all previous version from 4.1 -> 7.0? These are required and would be why the sessions are not showing up? https://exceptionless.com/docs/self-hosting/upgrading-self-hosted-instance/

**Comment by yuefengkai** [comment]
7.0 The new deployment has nothing to do with the old one




    


On 12/02/2020 23:41, Blake Niemyjski wrote: 
Did you run the migrations for all previous version from 4.1 -> 7.0? These are required and would be why the sessions are not showing up? https://exceptionless.com/docs/self-hosting/upgrading-self-hosted-instance/

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/exceptionless/Exceptionless/issues/792#issuecomment-737311811",
"url": "https://github.com/exceptionless/Exceptionless/issues/792#issuecomment-737311811",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by niemyjski** [comment]
It's really odd that you would have different results between the grid and the search header.  Due to what I see you posted (tons of data and api activity) I'd recommend setting up a second api and ui instance (with jobs disabled) and point it to this exceptionless instance (e.g., connection string etc...) Then with `Verbose` logging enabled. Hit the count endpoint that this dashboard calls and post the two search queries that are executed. There will be one to the stacks and one to events and it will look something like this:

```json
POST /dev-stacks/_search?pretty=true&error_trace=true&typed_keys=true&ignore_unavailable=true
{
  "_source": false,
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "must": [
              {
                "term": {
                  "is_deleted": {
                    "value": false
                  }
                }
              },
              {
                "range": {
                  "last_occurrence": {
                    "gte": "2020-11-30T15:40:19.952577Z"
                  }
                }
              },
              {
                "term": {
                  "project": {
                    "value": "5fc906e363826cb461115c56"
                  }
                }
              },
              {
                "term": {
                  "type": {
                    "value": "session"
                  }
                }
              },
              {
                "term": {
                  "project_id": {
                    "value": "5fc906e363826cb461115c56"
                  }
                }
              },
              {
                "range": {
                  "last_occurrence": {
                    "gte": "now/d-3d",
                    "lte": "now/d+1d"
                  }
                }
              }
            ]
          }
        }
      ]
    }
  },
  "size": 10000,
  "track_total_hits": true
}
```


```json
POST /dev-events-2020.11.30%2Cdev-events-2020.12.01%2Cdev-events-2020.12.02%2Cdev-events-2020.12.03/_search?pretty=true&error_trace=true&typed_keys=true&ignore_unavailable=true
{
  "_source": {
    "excludes": [
      "idx",
      "ip",
      "os",
      "error"
    ]
  },
  "aggs": {
    "avg_value": {
      "avg": {
        "field": "value"
      },
      "meta": {
        "@field_type": "double"
      }
    },
    "cardinality_user": {
      "cardinality": {
        "field": "data.@user.identity.keyword"
      }
    },
    "date_date": {
      "aggs": {
        "cardinality_user": {
          "cardinality": {
            "field": "data.@user.identity.keyword"
          }
        }
      },
      "date_histogram": {
        "extended_bounds": {
          "max": "2020-12-03T15:41:36.506931Z",
          "min": "2020-11-30T15:40:19.952577Z"
        },
        "field": "date",
        "fixed_interval": "43m",
        "format": "date_optional_time",
        "min_doc_count": 0,
        "time_zone": "-06:00"
      },
      "meta": {
        "@timezone": "-360m"
      }
    }
  },
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "must": [
              {
                "range": {
                  "date": {
                    "gte": "2020-11-30T15:40:19.952577Z",
                    "lte": "2020-12-03T15:41:36.506931Z"
                  }
                }
              },
              {
                "term": {
                  "project": {
                    "value": "5fc906e363826cb461115c56"
                  }
                }
              },
              {
                "match": {
                  "type": {
                    "query": "session"
                  }
                }
              },
              {
                "term": {
                  "project_id": {
                    "value": "5fc906e363826cb461115c56"
                  }
                }
              },
              {
                "range": {
                  "date": {
                    "gte": "now/d-3d",
                    "lte": "now/d+1d"
                  }
                }
              },
              {
                "term": {
                  "stack_id": {
                    "value": "none"
                  }
                }
              }
            ]
          }
        }
      ]
    }
  },
  "size": 0,
  "track_total_hits": true
}
```

If you could also post the query that's generated for the grid call to the events end point that would be great too. Please feel free to change any identifiers to `abc1`, `abc2`, respectively. I'm trying to see if maybe resolving stack status is the issue here.

**Comment by yuefengkai** [comment]
```
version: '3.7'

services:
  api:
    depends_on:
      - redis
    image: exceptionless/api:7.0.7
    environment:
      EX_AppMode: Production
      EX_BaseURL: http://162.168.1.188:5100 #URL to UI
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://162.168.1.188:9200;username=elastic;password=123456;
      EX_ConnectionStrings__Email: smtps://aa%40bb.com:123456@bb.com:25
      EX_ConnectionStrings__MessageBus: provider=redis
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
      EX_ApiThrottleLimit: 2147483647 
      EX_BotThrottleLimit: 2147483647
      EX_MaximumEventPostSize: 2147483647
      EX_AppScope: exceptionless
      EX_RunJobsInProcess: 'false'
      EX_ExceptionlessApiKey: NknDjT2ULrWK0dKdNAFVE0QAw7J2wuYPZ2Z0jMYt
      EX_ExceptionlessServerUrl: http://162.168.1.188:5000
      TZ: Asia/Shanghai
    ports:
      - 5000:80
    volumes:
      - appdata:/app/storage

  jobs:
    depends_on:
      - api
    image: exceptionless/job:7.0.7
    environment:
      EX_AppMode: Production
      EX_BaseURL: http://162.168.1.188:5100
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://162.168.1.188:9200;username=elastic;password=123456;
      EX_ConnectionStrings__Email: smtps://aa%40bb.com:123456@bb.com:25
      EX_ConnectionStrings__MessageBus: provider=redis
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
      EX_AppScope: exceptionless
      EX_ExceptionlessApiKey: NknDjT2ULrWK0dKdNAFVE0QAw7J2wuYPZ2Z0jMYt
      EX_ExceptionlessServerUrl: http://162.168.1.188:5000
      TZ: Asia/Shanghai
    volumes:
      - appdata:/app/storage

  ui:
    image: exceptionless/ui:3.0.7
    environment:
      AppMode: Development
      EX_ApiUrl: http://162.168.1.188:5000
      TZ: Asia/Shanghai
      #EX_Html5Mode: 'false'
      #EX_EnableSsl: 'false'
      #EX_EnableAccountCreation: 'false'
    ports:
      - 5100:80 

  redis:
    image: redis:5.0-alpine
    ports:
      - 6379:6379

volumes:
  esdata7:
    driver: local
  appdata:
    driver: local
  ssldata:
    driver: local
 
```

docker-compose redeploys, still no UserSession
