### ISSUE TITLE
The self-hosted account can’t log in for a few days and needs to re-register

### ISSUE THREAD

**Issue by liguob666** [exceptionless/Exceptionless#877]
I encountered it twice and the registered account was automatically cancelled. Do I need to add or modify any configuration? I wrote a lot of test exceptions and test logs. After canceling the account, how do I find out what data? After the deployment is successful, is there a super administrator who can enter the system to perform some basic configuration and visual configuration?

I use the following yml file for docker-compose for deployment. Are there many problems?

```yml
`version: '3.5'

# NOTE: This docker-compose file is for running services required to work on Exceptionless.
# For self-hosting, look here: https://github.com/exceptionless/Exceptionless/tree/master/samples

services:
  elasticsearch:
    image: exceptionless/elasticsearch:7.10.0
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata7:/usr/share/elasticsearch/data

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:7.10.0
    ports:
      - 5601:5601

  redis:
    image: redis:6.0-alpine
    ports:
      - 6379:6379
  
  app:
    depends_on:
      - elasticsearch
      - redis
    image: exceptionless/app:latest
    environment:
      EX_AppMode: Production
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://52.139.131.233:9200
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
      #ASPNETCORE_URLS: http://+;https://+
      #ASPNETCORE_HTTPS_PORT: 5001
      #ASPNETCORE_Kestrel__Certificates__Default__Password: password
      #ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      EX_RunJobsInProcess: 'false'
    ports:
      - 5000:80
    volumes:
      - appdata:/app/storage
  
  jobs:
    depends_on:
      - app
    image: exceptionless/job:latest
    environment:
      EX_AppMode: Production
      EX_BaseURL: http://52.139.231.233:5100
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://52.139.131.233:9200
      #EX_ConnectionStrings__Email: smtps://user:password@smtp.host.com:587
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
    volumes:
      - appdata:/app/storage
  
  ui:
    image: exceptionless/ui:latest
    environment:
      AppMode: Development
      EX_ApiUrl: http://52.139.131.233:5000
      EX_Html5Mode: 'true'
    ports:
      - 5100:80

  ready:
    image: dadarek/wait-for-dependencies
    command: elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  esdata7:
    driver: local
  appdata:
    driver: local`
```
