### ISSUE TITLE
7.1.0 elasticsearch error

### ISSUE THREAD

**Issue by PhyxionNL** [exceptionless/Exceptionless#961]
I've just tried updating 7.0.9 to 7.1.0 but exceptionless app fails:

```` Running Exceptionless Job dotnet Exceptionless.Web.dll
Starting Elasticsearch...

chown: invalid user: 'elasticsearch:elasticsearch'
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'Exceptionless.Job.dll' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download
````
I'm using a similar config as https://github.com/exceptionless/Exceptionless/blob/master/samples/docker-compose.yml

E: Downgrading to 7.0.9 makes it run again.

**Comment by niemyjski** [comment]
@ejsmith Can you take a look into this.

**Comment by PhyxionNL** [comment]
I could update Elastic itself to 7.14.0 while running 7.0.9 app + job. It seems a bit odd that App tries to run Job, in 7.0.9 this DLL is not present. Maybe the image is mistaken for the all in one?

**Comment by niemyjski** [comment]
Would you mind sharing your configuration file minus the connection strings.

**Comment by PhyxionNL** [comment]
Here's the file (now at 7.0.9 again)

```yaml
version: '3.7'

services:
  app:
    depends_on:
      - elasticsearch
      - redis
    image: exceptionless/app:7.0.9
    environment:
      EX_AppMode: Production
      #ASPNETCORE_URLS: http://+;https://+
      #ASPNETCORE_HTTPS_PORT: 5001
      #ASPNETCORE_Kestrel__Certificates__Default__Password: password
      #ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      EX_RunJobsInProcess: 'false'
      EX_EnableAccountCreation: 'false'
      EX_EnableArchive: 'false'
    ports:
      - 15080:80
      - 15443:443
    volumes:
      - exceptionless_appdata:/app/storage
      - exceptionless_ssldata:/https

  jobs:
    depends_on:
      - app
    image: exceptionless/job:7.0.9
    environment:
      EX_AppMode: Production
      EX_BaseURL: http://localhost
    volumes:
      - exceptionless_appdata:/app/storage

  elasticsearch:
    image: exceptionless/elasticsearch:7.14.0
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'
      bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: -Xms2g -Xmx2g
    ports:
      - 19200:9200
      - 19300:9300
    volumes:
      - exceptionless_elastic7:/usr/share/elasticsearch/data

  redis:
    image: redis:6.2.5-alpine
    ports:
      - 16379:6379
```
